export const QUERY_KEYS = {
  PRODUCTS: ["products"],
  PRODUCT: ["product"],
  CATEGORIES: ["categories"],
  ORDERS: ["orders"],
  ORDER: ["order"],
  USER_ORDERS: ["user-orders"],
  PAYMENTS: ["payments"],
  PAYMENT: ["payment"],
  INVENTORY: ["inventory"],
  NOTIFICATIONS: ["notifications"],
  SUBSCRIBERS: ["subscribers"],
  USERS: ["users"],
  DASHBOARD: ["dashboard"],
};
