spring.application.name=api-gateway

server.port=8080

spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=http://auth-service:8081

spring.cloud.gateway.mvc.routes[1].id=product-service
spring.cloud.gateway.mvc.routes[1].uri=http://product-service:8082

spring.cloud.gateway.mvc.routes[2].id=inventory-service
spring.cloud.gateway.mvc.routes[2].uri=http://inventory-service:8083
